'use strict';
const H = require('./helpers');
const fs = require('fs');
const path = require('path');
const { createStore } = require('../src/main/store');
const { createTimer } = require('../src/main/timer');
const util = require('../src/main/util');
const stats = require('../src/shared/statistics');
const day = '2026-09-09', key = 'sisy-focus-state-v2';
const clock = H.fakeClock(new Date(day + 'T12:00:00').getTime());
const dir = H.mkTmp('workflow');
let store = createStore({ dir, log() {}, warn() {} }); store.load();
const tasks = ['a', 'b', 'c'].map(id => ({ id, title: 'Task ' + id, done: id === 'c', subtasks: [] }));
store.set(key, { viewDay: day, days: { [day]: { tasks, dismissedDaily: {} } } });
const make = () => { const t = createTimer({ store, date: { todayKey: () => util.todayKey(new Date(clock.wall)), normalizeKey: util.normalizeKey }, now: clock.now, mono: clock.monoNow, log() {} }); t.init(); t.pauseTicker(); return t; };
let timer = make();
H.group('Atomic task binding and persisted history');
for (const ref of [null, {}, {id:'missing',day}, {id:'c',day}, {id:'a',day:'2026-09-08'}]) H.eq(timer.startTask(ref).ok, false, 'Invalid or completed task rejected: ' + JSON.stringify(ref));
H.eq(timer.snapshot().smState, 'idle', 'Rejected references leave timer idle');
H.eq(timer.startTask({id:'a',day,title:'forged'}).ok, true, 'Start task A');
H.eq(timer.snapshot().timer.task.title, 'Task a', 'Title resolved from authoritative task');
const started = timer.snapshot().timer.startedAt;
H.eq(timer.startTask({id:'a',day}).ok, true, 'Double click is idempotent');
H.eq(timer.snapshot().timer.startedAt, started, 'Double click retains original start');
clock.advance(60000);
timer.flush(); store.flush();
const beforeDisk = fs.readFileSync(path.join(dir,'sisy-store.json'),'utf8');
const before = JSON.stringify(timer.snapshot());
H.eq(timer.startTask({id:'b',day}).code, 'timer-busy', 'Different task rejected while running');
H.eq(JSON.stringify(timer.snapshot()), before, 'Busy request changes no state');
H.eq(fs.readFileSync(path.join(dir,'sisy-store.json'),'utf8'), beforeDisk, 'Busy request changes no disk data');
timer.command('pause');
H.eq(timer.startTask({id:'b',day}).ok, false, 'Paused round cannot be rebound');
clock.advance(30000);
timer.flush(); store.flush();
store = createStore({dir,log(){},warn(){}}); store.load(); timer = make();
H.eq(timer.snapshot().timer.task.id, 'a', 'Restart preserves task context');
H.eq(timer.startTask({id:'a',day}).ok, true, 'Same task resumes after restart');
H.eq(timer.snapshot().timer.pausedMs, 30000, 'Resume accounts for pause across restart');
store.set('sisy-active-task', {id:'b',day,title:'Loose legacy key'});
const renamed = store.get(key); renamed.days[day].tasks = renamed.days[day].tasks.filter(t => t.id !== 'a'); store.set(key, renamed);
clock.advance(1441000); timer.command('refresh');
let history = timer.getHistory();
H.eq(history.length, 1, 'Completion stored exactly once');
H.eq(history[0].taskId, 'a', 'Deletion and loose key cannot reassign history');
H.eq(history[0].taskDay, day, 'History retains task date');
H.eq(history[0].taskTitle, 'Task a', 'History retains title snapshot');
H.eq(timer.snapshot().timer.task, null, 'Completed round clears binding');
timer.command('refresh'); H.eq(timer.getHistory().length, 1, 'Repeat refresh cannot double count');
store.flush(); store = createStore({dir,log(){},warn(){}}); store.load(); timer = make();
H.eq(timer.getHistory()[0].taskDay, day, 'History schema round trips to disk');
timer.command('setPhase',{phase:'short'});
H.eq(timer.startTask({id:'b',day}).ok, true, 'Task may start from idle break');
H.eq(timer.snapshot().timer.phase, 'focus', 'Task starts focus phase');
timer.command('abandon');
H.eq(timer.getHistory().filter(h=>h.taskId==='b'&&h.result==='abandoned').length, 1, 'Abandon keeps correct task attribution');
H.eq(stats.taskTotals(timer.getHistory())[day+'/a'], 25, 'Completed minutes assigned to task');
H.eq(stats.taskTotals(timer.getHistory())[day+'/b'], undefined, 'Abandoned minutes excluded');

H.group('Calendar statistics, recovered rounds and all hours');
const entry = (d, hour, result='done', phase='focus', n=25) => ({day:d,startedAt:d+'T'+String(hour).padStart(2,'0')+':00:00',finishedAt:d+'T'+String(hour).padStart(2,'0')+':30:00',result,phase,plannedMinutes:n});
const now = new Date('2026-09-09T23:59:00');
const hs = [entry('2026-08-31',9),entry('2026-09-01',9),entry('2026-09-06',9),entry('2026-09-07',1),entry('2026-09-08',23,'recovered'),entry(day,13),entry(day,4,'abandoned'),entry(day,4,'done','short'),entry('2026-09-10',9)];
const records = {'2026-09-01':{tasks:[{done:true}]},'2026-09-07':{tasks:[{done:true},{done:false}]}};
const snapshot = JSON.stringify([hs,records]);
const week = stats.summary(hs, records, 'week', now), month = stats.summary(hs,records,'month',now);
H.eq(week.since, '2026-09-07', 'Week starts on Monday');
H.eq(week.minutes, 75, 'Week excludes last Sunday, abandoned, rest and future');
H.eq(week.rounds, 3, 'Recovered completion included');
H.eq(week.tasks, 1, 'Task count uses calendar week');
H.eq(month.since, '2026-09-01', 'Month starts on first');
H.eq(month.minutes, 125, 'Calendar month is not rolling 30 days');
H.eq(month.tasks, 2, 'Month task count');
H.eq(week.hours[23], 25, 'Late-night recovered session included');
H.eq(week.bins[0], 25, 'Odd hour 01 is included');
H.eq(week.bins[6], 25, 'Odd hour 13 is included');
H.eq(week.bins[11], 25, '23 hour is included');
H.eq(week.bins.reduce((a,b)=>a+b,0), week.minutes, 'All chart bins conserve credited minutes');
H.eq(week.streak, 4, 'Streak crosses period boundary');
H.eq(JSON.stringify([hs,records]), snapshot, 'Statistics never mutate records');
const allHours = Array.from({length:24},(_,i)=>entry(day,i,'done','focus',i+1));
const all = stats.summary(allHours,{},'week',now);
H.eq(all.hours.length,24,'24 hours represented');
H.eq(all.bins.reduce((a,b)=>a+b,0),300,'Every hour contributes once');
H.eq(all.peakIndex,11,'Peak covers last two hours');
H.eq(stats.summary([],{},'week',now).peakIndex,-1,'Empty history has no invented peak');
H.eq(stats.summary([],{},'week',new Date('2027-01-01T12:00:00')).since,'2026-12-28','Week spans year boundary');
H.eq(stats.summary(hs,{},'week',new Date('2026-09-09T00:00:00')).streak,3,'Yesterday keeps current streak alive');
H.eq(stats.summary([entry('2026-09-06',9)],{},'week',now).streak,0,'Older streak is not current streak');
const long = Array.from({length:140},(_,i)=>{const d=new Date(now);d.setDate(d.getDate()-i);return entry(util.todayKey(d),9);});
H.eq(stats.summary(long,{},'week',now).streak,140,'No arbitrary 120 day streak cap');
H.eq(stats.taskTotals([{...hs[3],taskId:'a'}])[day+'/a'],undefined,'Undated legacy task references are not guessed');

H.group('Ordering and read-only statistics');
require('../src/shared/date'); require('../src/todo/state');
const mem = new Map(); const clone=x=>x==null?x:JSON.parse(JSON.stringify(x));
const localStore={get:(k,f)=>mem.has(k)?clone(mem.get(k)):f,set:(k,v)=>{mem.set(k,clone(v));return true;},remove:k=>mem.delete(k)};
const date = {...globalThis.DSH.date,todayKey:()=>day};
const create = () => globalThis.DSH.todo.createState({store:localStore,date,log:{info(){},warn(){},error(){}}}).init();
localStore.set(key,{viewDay:day,days:{[day]:{tasks,dismissedDaily:{}}}});
let state=create(); const order=()=>state.tasks().map(t=>t.id).join(',');
state.moveTask('a','c',true); H.eq(order(),'b,c,a','Move after last row');
state.moveTask('a','b',false); H.eq(order(),'a,b,c','Move before first row');
state.moveTask('a',null); H.eq(order(),'b,c,a','Whitespace drop moves to end');
state.moveTask('b','missing'); H.eq(order(),'b,c,a','Invalid target cannot lose task');
state=create(); H.eq(order(),'b,c,a','Order survives reopening');
const recordsBefore=JSON.stringify(state.records()); state.dayStats('2026-01-01');
H.eq(JSON.stringify(state.records()),recordsBefore,'Reading calendar statistics creates no empty days');
state.setViewDay('2026-09-08');
const old=JSON.stringify(state.records()); state.moveTask('a',null);
H.eq(JSON.stringify(state.records()),old,'Historical task order cannot be changed');
timer.pauseTicker();
H.finish();
